Categories = {
			  [0] = GetLabelText('VEH_CLASS_0'),	--Compacts
			  [1] = GetLabelText('VEH_CLASS_1'),	--Sedans
			  [2] = GetLabelText('VEH_CLASS_2'),	--SUVs
			  [3] = GetLabelText('VEH_CLASS_3'),	--Coupes
			  [4] = GetLabelText('VEH_CLASS_4'),	--Muscle
			  [5] = GetLabelText('VEH_CLASS_5'),	--Sports Classics
			  [6] = GetLabelText('VEH_CLASS_6'),	--Sports
			  [7] = GetLabelText('VEH_CLASS_7'),	--Super
			  [8] = GetLabelText('VEH_CLASS_8'),	--Motorcycles
			  [9] = GetLabelText('VEH_CLASS_9'),	--Off-road
			  [10] = GetLabelText('VEH_CLASS_10'),	--Industrial
			  [11] = GetLabelText('VEH_CLASS_11'),	--Utility
			  [12] = GetLabelText('VEH_CLASS_12'),	--Vans
			  [13] = GetLabelText('VEH_CLASS_13'),	--Cycles
			  [14] = GetLabelText('VEH_CLASS_14'),	--Boats
			  [15] = GetLabelText('VEH_CLASS_15'),	--Helicopters
			  [16] = GetLabelText('VEH_CLASS_16'),	--Planes
			  [17] = GetLabelText('VEH_CLASS_17'),	--Service
			  [18] = GetLabelText('VEH_CLASS_18'),	--Emergency
			  [19] = GetLabelText('VEH_CLASS_19'),	--Military
			  [20] = GetLabelText('VEH_CLASS_20'),	--Commercial
			  [21] = GetLabelText('VEH_CLASS_21'),	--Trains
			  [22] = GetLabelText('TRAILER'), 		--Trailers
			  [23] = 'Motorcycle Pack',
			  [24] = 'Mazda',
			  [25] = 'Nissan',
			  [26] = 'Toyota',
			  [27] = 'BMW',
			  [28] = 'Honda',
			  [29] = 'Lexus',
			  [30] = 'Volkswagen',
			  [31] = 'Subaru',
                          [32] = 'Bikes',
                          [33] = 'Range Rover',
                          [34] = 'Mercedes Benz',
                          [35] = 'Ferrari',
                          [36] = 'Vanilla',
                          [37] = 'Porsche',
                          [38] = 'Bugatti',
                          [39] = 'Kia',
                          [40] = 'Henry Clay',
                          [41] = 'Opel',
                          [42] = 'Aston Martin',
                          [43] = 'Mclaren',
                          [44] = 'Koenigsegg',
                          [45] = 'Lamborghini',
                          [46] = 'Ford',
                          [47] = 'Jeep',
                          [48] = 'Audi',
                          [49] = 'Mitsubishi',
                          [50] = 'Alpine',
                          [51] = 'Chevrolet',
                          [52] = 'Renault',
                          [53] = 'Saleen',
                          [54] = 'TVR',
                          [55] = 'Rolls Royce',
                          [56] = 'Pagani',
                          [57] = 'Boats',
                          [58] = 'Five-O',
                          [59] = 'Acura',
                          [60] = 'Hyundai',
                          [61] = 'Mini',
			  [62] = 'RAM',
			  [63] = 'Vanilla Edits',
			  [64] = 'ISUZU',
			  [65] = 'International',
			  [66] = 'Polaris',
			  [67] = 'GMC',
			  [68] = "Skoda",
			  [69] = "Peugeot",
			  [70] = "Maserati",
			  [71] = "Dodge",
			  [72] = "Infiniti",
			  [73] = "Bentley",
			  [74] = "Lincoln",
                         }
